services:
  postgres:
    image: postgres:17-alpine
    container_name: server-monitoring-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS : "--encoding=UTF8 --data-checksums"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d server_monitoring"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
        # By default postgres runs everything for the 1st time with .sql or .sh inside the /docker-entrypoint-initdb.d/
      - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    networks:
      - website-monitoring-network
    restart: unless-stopped
  
  mongo:
    image: mongo:6.0
    container_name: server-monitoring-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - website-monitoring-network
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: server-monitoring-rabbitmq
    environment:
       RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
       RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - website-monitoring-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: api-monitoring-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - website-monitoring-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy   

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  rabbitmq_data :
    driver: local
  pgadmin_data :
    driver : local
  
networks:
  website-monitoring-network :
    driver: bridge
  
  

